apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  annotations:
    # mandatory annotation
    harness.io/project-url: https://app.harness.io/ng/#/account/Npsd6WrETY-Baq6iHeOHGw/home/orgs/default/projects/default_project/

  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user  
spec:
  type: service
  lifecycle: experimental
  owner: guests
